// Актуальный пул Dota 2: 127 героев по официальному datafeed/herolist.
const HEROES = [
  { name: "Anti-Mage", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/antimage.png" },
  { name: "Axe", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/axe.png" },
  { name: "Bane", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bane.png" },
  { name: "Bloodseeker", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bloodseeker.png" },
  { name: "Crystal Maiden", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/crystal_maiden.png" },
  { name: "Drow Ranger", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/drow_ranger.png" },
  { name: "Earthshaker", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earthshaker.png" },
  { name: "Juggernaut", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/juggernaut.png" },
  { name: "Mirana", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mirana.png" },
  { name: "Shadow Fiend", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nevermore.png" },
  { name: "Morphling", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/morphling.png" },
  { name: "Phantom Lancer", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_lancer.png" },
  { name: "Puck", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/puck.png" },
  { name: "Pudge", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pudge.png" },
  { name: "Razor", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/razor.png" },
  { name: "Sand King", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sand_king.png" },
  { name: "Storm Spirit", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/storm_spirit.png" },
  { name: "Sven", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sven.png" },
  { name: "Tiny", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tiny.png" },
  { name: "Vengeful Spirit", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/vengefulspirit.png" },
  { name: "Windranger", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/windrunner.png" },
  { name: "Zeus", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/zuus.png" },
  { name: "Kunkka", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/kunkka.png" },
  { name: "Lina", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lina.png" },
  { name: "Lich", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lich.png" },
  { name: "Lion", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lion.png" },
  { name: "Shadow Shaman", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_shaman.png" },
  { name: "Slardar", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slardar.png" },
  { name: "Tidehunter", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tidehunter.png" },
  { name: "Witch Doctor", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/witch_doctor.png" },
  { name: "Riki", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/riki.png" },
  { name: "Enigma", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enigma.png" },
  { name: "Tinker", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tinker.png" },
  { name: "Sniper", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/sniper.png" },
  { name: "Necrophos", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/necrolyte.png" },
  { name: "Warlock", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/warlock.png" },
  { name: "Beastmaster", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/beastmaster.png" },
  { name: "Queen of Pain", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/queenofpain.png" },
  { name: "Venomancer", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/venomancer.png" },
  { name: "Faceless Void", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/faceless_void.png" },
  { name: "Wraith King", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skeleton_king.png" },
  { name: "Death Prophet", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/death_prophet.png" },
  { name: "Phantom Assassin", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phantom_assassin.png" },
  { name: "Pugna", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pugna.png" },
  { name: "Templar Assassin", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/templar_assassin.png" },
  { name: "Viper", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/viper.png" },
  { name: "Luna", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/luna.png" },
  { name: "Dragon Knight", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dragon_knight.png" },
  { name: "Dazzle", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dazzle.png" },
  { name: "Clockwerk", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rattletrap.png" },
  { name: "Leshrac", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/leshrac.png" },
  { name: "Nature's Prophet", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/furion.png" },
  { name: "Lifestealer", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/life_stealer.png" },
  { name: "Dark Seer", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_seer.png" },
  { name: "Clinkz", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/clinkz.png" },
  { name: "Omniknight", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/omniknight.png" },
  { name: "Enchantress", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/enchantress.png" },
  { name: "Huskar", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/huskar.png" },
  { name: "Night Stalker", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/night_stalker.png" },
  { name: "Broodmother", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/broodmother.png" },
  { name: "Bounty Hunter", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bounty_hunter.png" },
  { name: "Weaver", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/weaver.png" },
  { name: "Jakiro", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/jakiro.png" },
  { name: "Batrider", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/batrider.png" },
  { name: "Chen", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chen.png" },
  { name: "Spectre", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spectre.png" },
  { name: "Doom", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/doom_bringer.png" },
  { name: "Ancient Apparition", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ancient_apparition.png" },
  { name: "Ursa", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ursa.png" },
  { name: "Spirit Breaker", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/spirit_breaker.png" },
  { name: "Gyrocopter", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/gyrocopter.png" },
  { name: "Alchemist", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/alchemist.png" },
  { name: "Invoker", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/invoker.png" },
  { name: "Silencer", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/silencer.png" },
  { name: "Outworld Destroyer", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/obsidian_destroyer.png" },
  { name: "Lycan", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lycan.png" },
  { name: "Brewmaster", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/brewmaster.png" },
  { name: "Shadow Demon", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shadow_demon.png" },
  { name: "Lone Druid", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/lone_druid.png" },
  { name: "Chaos Knight", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/chaos_knight.png" },
  { name: "Meepo", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/meepo.png" },
  { name: "Treant Protector", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/treant.png" },
  { name: "Ogre Magi", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ogre_magi.png" },
  { name: "Undying", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/undying.png" },
  { name: "Rubick", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/rubick.png" },
  { name: "Disruptor", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/disruptor.png" },
  { name: "Nyx Assassin", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/nyx_assassin.png" },
  { name: "Naga Siren", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/naga_siren.png" },
  { name: "Keeper of the Light", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/keeper_of_the_light.png" },
  { name: "Io", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/wisp.png" },
  { name: "Visage", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/visage.png" },
  { name: "Slark", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/slark.png" },
  { name: "Medusa", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/medusa.png" },
  { name: "Troll Warlord", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/troll_warlord.png" },
  { name: "Centaur Warrunner", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/centaur.png" },
  { name: "Magnus", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/magnataur.png" },
  { name: "Timbersaw", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/shredder.png" },
  { name: "Bristleback", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/bristleback.png" },
  { name: "Tusk", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/tusk.png" },
  { name: "Skywrath Mage", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/skywrath_mage.png" },
  { name: "Abaddon", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abaddon.png" },
  { name: "Elder Titan", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/elder_titan.png" },
  { name: "Legion Commander", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/legion_commander.png" },
  { name: "Ember Spirit", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ember_spirit.png" },
  { name: "Earth Spirit", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/earth_spirit.png" },
  { name: "Terrorblade", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/terrorblade.png" },
  { name: "Phoenix", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/phoenix.png" },
  { name: "Oracle", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/oracle.png" },
  { name: "Techies", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/techies.png" },
  { name: "Winter Wyvern", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/winter_wyvern.png" },
  { name: "Arc Warden", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/arc_warden.png" },
  { name: "Underlord", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/abyssal_underlord.png" },
  { name: "Monkey King", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/monkey_king.png" },
  { name: "Pangolier", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/pangolier.png" },
  { name: "Dark Willow", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dark_willow.png" },
  { name: "Grimstroke", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/grimstroke.png" },
  { name: "Mars", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/mars.png" },
  { name: "Void Spirit", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/void_spirit.png" },
  { name: "Snapfire", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/snapfire.png" },
  { name: "Hoodwink", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/hoodwink.png" },
  { name: "Dawnbreaker", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/dawnbreaker.png" },
  { name: "Marci", attr: "all", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/marci.png" },
  { name: "Primal Beast", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/primal_beast.png" },
  { name: "Muerta", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/muerta.png" },
  { name: "Ringmaster", attr: "int", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/ringmaster.png" },
  { name: "Kez", attr: "agi", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/kez.png" },
  { name: "Largo", attr: "str", img: "https://cdn.cloudflare.steamstatic.com/apps/dota2/images/dota_react/heroes/largo.png" }
];
